In [0]:
#Import Packages
#Linear Algebra
import numpy as np
#Data Processing
import pandas as pd
import sklearn
#Data Visualization
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import roc_curve,auc,recall_score,precision_score,accuracy_score,f1_score
from sklearn.metrics import confusion_matrix,average_precision_score,recall_score
from sklearn import svm


In [0]:
#To print many statements at the same time using below command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [0]:
# Import datset and create a dataframe
df=pd.read_csv("winequality-red.csv")
df.head()
df.tail()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[5 rows x 12 columns]

In [0]:
# importing one hot encoder from sklearn 
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(df['quality'])
list(le.classes_)
dfn = le.transform(df['quality'])
le.inverse_transform([0,1,2,3,4,5])
df['Y'] =dfn

LabelEncoder()

[3, 4, 5, 6, 7, 8]

array([3, 4, 5, 6, 7, 8])

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 13 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
Y                       1599 non-null int64
dtypes: float64(11), int64(2)
memory usage: 162.5 KB


In [0]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Y
0            7.4              0.70         0.00  ...      9.4        5  2
1            7.8              0.88         0.00  ...      9.8        5  2
2            7.8              0.76         0.04  ...      9.8        5  2
3           11.2              0.28         0.56  ...      9.8        6  3
4            7.4              0.70         0.00  ...      9.4        5  2

[5 rows x 13 columns]

In [0]:
df.describe()

fixed acidity  volatile acidity  ...      quality            Y
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...     5.636023     2.636023
std         1.741096          0.179060  ...     0.807569     0.807569
min         4.600000          0.120000  ...     3.000000     0.000000
25%         7.100000          0.390000  ...     5.000000     2.000000
50%         7.900000          0.520000  ...     6.000000     3.000000
75%         9.200000          0.640000  ...     6.000000     3.000000
max        15.900000          1.580000  ...     8.000000     5.000000

[8 rows x 13 columns]

In [0]:
#Missing Value Count
total=df.isnull().sum().sort_values(ascending=False)
per=df.isnull().sum()/df.isnull().count()*100
percentage=(round(per,2)).sort_values(ascending=False)
missing_data=pd.concat([total,percentage],axis=1,keys=['Total','%'])
missing_data

Total    %
Y                         0  0.0
quality                   0  0.0
alcohol                   0  0.0
sulphates                 0  0.0
pH                        0  0.0
density                   0  0.0
total sulfur dioxide      0  0.0
free sulfur dioxide       0  0.0
chlorides                 0  0.0
residual sugar            0  0.0
citric acid               0  0.0
volatile acidity          0  0.0
fixed acidity             0  0.0

In [0]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Y'],
      dtype='object')

In [0]:
#Creating independent and dependent variable
x1 =df.drop('quality', axis = 1)
x = x1.drop('Y', axis = 1)
y=df['Y']
x.head()
x.shape
y.head()
y.shape

fixed acidity  volatile acidity  citric acid  ...    pH  sulphates  alcohol
0            7.4              0.70         0.00  ...  3.51       0.56      9.4
1            7.8              0.88         0.00  ...  3.20       0.68      9.8
2            7.8              0.76         0.04  ...  3.26       0.65      9.8
3           11.2              0.28         0.56  ...  3.16       0.58      9.8
4            7.4              0.70         0.00  ...  3.51       0.56      9.4

[5 rows x 11 columns]

(1599, 11)

0    2
1    2
2    2
3    3
4    2
Name: Y, dtype: int64

(1599,)

In [0]:
#Creating train and test data 75% and 25% split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.25,random_state=1)
train_x.shape
test_x.shape
train_y.shape
test_y.shape

(1199, 11)

(400, 11)

(1199,)

(400,)

In [0]:
test_y.value_counts()

2    171
3    167
4     42
1     16
5      3
0      1
Name: Y, dtype: int64

In [0]:
df['Y'].value_counts()

2    681
3    638
4    199
1     53
5     18
0     10
Name: Y, dtype: int64

In [0]:
train_x.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

**DECISION TREE**

In [0]:
# training a DescisionTreeClassifier 
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(train_x, train_y) 
dtree_predictions = dtree_model.predict(test_x)

In [0]:
# creating a confusion matrix 
cm = confusion_matrix(test_y, dtree_predictions) 
cm

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,  11,   5,   0,   0],
       [  0,   0, 150,  17,   4,   0],
       [  0,   0,  88,  52,  27,   0],
       [  0,   0,   6,  16,  20,   0],
       [  0,   0,   0,   0,   3,   0]])

In [0]:
print("Accuracy Score")
print(metrics.accuracy_score(test_y,dtree_predictions))
print("Precision/Recall Metrics")
print(metrics.classification_report(test_y,dtree_predictions))
print("AUC")
#auc_dtree=metrics.roc_auc_score(test_y,dtree_predictions)
#auc_dtree

Accuracy Score
0.555
Precision/Recall Metrics
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00        16
           2       0.59      0.88      0.70       171
           3       0.58      0.31      0.40       167
           4       0.37      0.48      0.42        42
           5       0.00      0.00      0.00         3

    accuracy                           0.56       400
   macro avg       0.26      0.28      0.25       400
weighted avg       0.53      0.56      0.51       400

AUC


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**SUPPORT VECTOR MACHINE**

In [0]:
# training a linear SVM classifier 
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(train_x, train_y) 
svm_predictions = svm_model_linear.predict(test_x)

In [0]:
# model accuracy for X_test   
accuracy = svm_model_linear.score(test_x, test_y) 
accuracy

0.595

In [0]:
# creating a confusion matrix 
cm = confusion_matrix(test_y, svm_predictions) 
cm

array([[  0,   0,   1,   0,   0,   0],
       [  0,   0,  12,   4,   0,   0],
       [  0,   0, 139,  32,   0,   0],
       [  0,   0,  68,  99,   0,   0],
       [  0,   0,   4,  38,   0,   0],
       [  0,   0,   0,   3,   0,   0]])

In [0]:
print("Accuracy Score")
print(metrics.accuracy_score(test_y,svm_predictions))
print("Precision/Recall Metrics")
print(metrics.classification_report(test_y,svm_predictions))
print("AUC")

Accuracy Score
0.595
Precision/Recall Metrics
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00        16
           2       0.62      0.81      0.70       171
           3       0.56      0.59      0.58       167
           4       0.00      0.00      0.00        42
           5       0.00      0.00      0.00         3

    accuracy                           0.59       400
   macro avg       0.20      0.23      0.21       400
weighted avg       0.50      0.59      0.54       400

AUC


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**K-Nearest Neighbours**

In [0]:
# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(train_x, train_y) 

In [0]:
# accuracy on X_test 
accuracy = knn.score(test_x, test_y) 
accuracy 

0.51

In [0]:
# creating a confusion matrix 
knn_predictions = knn.predict(test_x)  
cm = confusion_matrix(test_y, knn_predictions) 
cm

array([[  0,   0,   0,   1,   0,   0],
       [  0,   1,   9,   5,   1,   0],
       [  1,   1, 118,  46,   5,   0],
       [  0,   0,  81,  74,  12,   0],
       [  0,   0,  13,  18,  11,   0],
       [  0,   0,   1,   0,   2,   0]])

In [0]:
print("Accuracy Score")
print(metrics.accuracy_score(test_y,knn_predictions))
print("Precision/Recall Metrics")
print(metrics.classification_report(test_y,knn_predictions))
print("AUC")

Accuracy Score
0.51
Precision/Recall Metrics
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.06      0.11        16
           2       0.53      0.69      0.60       171
           3       0.51      0.44      0.48       167
           4       0.35      0.26      0.30        42
           5       0.00      0.00      0.00         3

    accuracy                           0.51       400
   macro avg       0.32      0.24      0.25       400
weighted avg       0.50      0.51      0.49       400

AUC


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**NAIVE BAYES CLASSIFIER**

In [0]:
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(train_x, train_y) 
gnb_predictions = gnb.predict(test_x) 

In [0]:
# accuracy on X_test 
accuracy = gnb.score(test_x, test_y) 
accuracy 

0.55

In [0]:
# creating a confusion matrix 
cm = confusion_matrix(test_y, gnb_predictions) 
cm

array([[  0,   1,   0,   0,   0,   0],
       [  1,   0,  10,   4,   1,   0],
       [  0,   6, 125,  31,   9,   0],
       [  0,   7,  55,  70,  33,   2],
       [  0,   0,   5,  12,  25,   0],
       [  0,   0,   0,   0,   3,   0]])

In [0]:
print("Accuracy Score")
print(metrics.accuracy_score(test_y,gnb_predictions))
print("Precision/Recall Metrics")
print(metrics.classification_report(test_y,gnb_predictions))
print("AUC")

Accuracy Score
0.55
Precision/Recall Metrics
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00        16
           2       0.64      0.73      0.68       171
           3       0.60      0.42      0.49       167
           4       0.35      0.60      0.44        42
           5       0.00      0.00      0.00         3

    accuracy                           0.55       400
   macro avg       0.27      0.29      0.27       400
weighted avg       0.56      0.55      0.54       400

AUC


**DEEP NEURAL NETWORK**

In [0]:
df1 = pd.read_csv("winequality-red.csv")

In [0]:
a = df1.drop("quality", axis = 1)

In [0]:
b = df1['quality']

In [0]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(b)
encoded_B = encoder.transform(b)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_b = np_utils.to_categorical(encoded_B)

LabelEncoder()

In [0]:
#Creating train and test data 75% and 25% split
train_x1,test_x1,train_y1,test_y1=train_test_split(a,dummy_b,test_size=0.25,random_state=1)
train_x1.shape
test_x1.shape
train_y1.shape
test_y1.shape

(1199, 11)

(400, 11)

(1199, 6)

(400, 6)

In [0]:
train_y1

array([[0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [0]:
# neural network with keras tutorial
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# define the keras model
model = Sequential()
model.add(Dense(20, input_dim=11, activation='relu'))
model.add(Dense(6, activation='softmax'))

In [0]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [0]:
# fit the keras model on the dataset
model.fit(train_x1,train_y1, epochs=200,verbose =2)

 - 0s - loss: 0.2828 - acc: 0.8632
Epoch 110/200
 - 0s - loss: 0.2819 - acc: 0.8609
Epoch 111/200
 - 0s - loss: 0.2830 - acc: 0.8607
Epoch 112/200
 - 0s - loss: 0.2819 - acc: 0.8607
Epoch 113/200
 - 0s - loss: 0.2837 - acc: 0.8607
Epoch 114/200
 - 0s - loss: 0.2810 - acc: 0.8622
Epoch 115/200
 - 0s - loss: 0.2847 - acc: 0.8606
Epoch 116/200
 - 0s - loss: 0.2810 - acc: 0.8627
Epoch 117/200
 - 0s - loss: 0.2819 - acc: 0.8645
Epoch 118/200
 - 0s - loss: 0.2849 - acc: 0.8609
Epoch 119/200
 - 0s - loss: 0.2814 - acc: 0.8649
Epoch 120/200
 - 0s - loss: 0.2825 - acc: 0.8571
Epoch 121/200
 - 0s - loss: 0.2883 - acc: 0.8563
Epoch 122/200
 - 0s - loss: 0.2827 - acc: 0.8602
Epoch 123/200
 - 0s - loss: 0.2838 - acc: 0.8614
Epoch 124/200
 - 0s - loss: 0.2819 - acc: 0.8620
Epoch 125/200
 - 0s - loss: 0.2834 - acc: 0.8577
Epoch 126/200
 - 0s - loss: 0.2842 - acc: 0.8602
Epoch 127/200
 - 0s - loss: 0.2812 - acc: 0.8622
Epoch 128/200
 - 0s - loss: 0.2805 - acc: 0.8614
Epoch 129/200
 - 0s - loss: 0.2819

In [0]:
# evaluate the keras model
_, accuracy = model.evaluate(train_x1, train_y1)
print('Accuracy: %.2f' % (accuracy*100))

1199/1199 [==============================] - 0s 24us/step
Accuracy: 86.74
